name: Terraform

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

defaults:
  run:
    working-directory: ./
    shell: bash

jobs:
  build_dev:
    uses: ./.github/workflows/tf-init.yaml
    with:
      stage: "dev"
      tfVersion: 1.3.6
      tenantId: "f1847c27-90be-4b38-a1b7-bd3a2029122f"
      subscriptionId: "d47fae4a-a9d1-44f7-a09e-23bb76696838"
    secrets: inherit
  build_prod:
    uses: ./.github/workflows/tf-init.yaml
    with:
      stage: "prod"
      tfVersion: 1.3.6
      tenantId: "f1847c27-90be-4b38-a1b7-bd3a2029122f"
      subscriptionId: "d47fae4a-a9d1-44f7-a09e-23bb76696838"
    secrets: inherit
  deploy_dev:
    needs: build_dev
    uses: ./.github/workflows/tf-apply.yaml
    with:
      stage: "dev"
      tfVersion: 1.3.6
      tenantId: "f1847c27-90be-4b38-a1b7-bd3a2029122f"
      subscriptionId: "d47fae4a-a9d1-44f7-a09e-23bb76696838"
    secrets: inherit
  deploy_prod:
    needs: build_prod
    uses: ./.github/workflows/tf-apply.yaml
    with:
      stage: "dev"
      tfVersion: 1.3.6
      tenantId: "f1847c27-90be-4b38-a1b7-bd3a2029122f"
      subscriptionId: "d47fae4a-a9d1-44f7-a09e-23bb76696838"
    secrets: inherit
