name: Terraform

on:
  push:
    branches:
     - main
     - dev
  pull_request:

env:
  tfVersion: 1.3.6
  tenantId: "f1847c27-90be-4b38-a1b7-bd3a2029122f"
  subscriptionId: "d47fae4a-a9d1-44f7-a09e-23bb76696838"

defaults:
  run:
    working-directory: ./
    shell: bash

jobs:
  build:
    strategy:
      matrix:
        stage: ['dev', 'prod']
    uses: ./.github/workflows/tf-init.yaml
    with:
      stage: ${{ matrix.stage }}
      tf_version: $tfVersion
      tenantId: $tenantId
      subscriptionId: $subscriptionId
  deploy:
    strategy:
      matrix:
        stage: ['dev', 'prod']
    uses: ./.github/workflows/tf-init.yaml
    with:
      stage: ${{ matrix.stage }}
      tf_version: $tfVersion
      tenantId: $tenantId
      subscriptionId: $subscriptionId
